const getData = () => {
    try {
        
    } catch (error) {
        
    }
}